# Generated by Django 5.2 on 2025-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("clasificacion", models.CharField(max_length=10)),
                ("anio_estreno", models.IntegerField()),
                ("duracion", models.IntegerField(help_text="Duración en minutos")),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("Comedia", "Comedia"),
                            ("Romance", "Romance"),
                            ("Aventura", "Aventura"),
                            ("Terror", "Terror"),
                            ("Acción", "Acción"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
